### PR TITLE
Port to use LibHandy

### PR DESCRIPTION
**Pull request by lainsce**
This ports Tasks to use LibHandy, and consequently makes it look not broken.

Looks like:
tasks

### CODE REVIEW

**Comment by lainsce** [comment]
There's going to be a follow-up PR where I fix header coloring (Scheduled should be using another color, so does the others than default Blue)

**Comment by alainm23** [comment]
What happened to Gtk.Paned?

**Comment by lainsce** [comment]
Gtk.Paned doesn't really work for the full sidebar look and is prone to visual bugs such as its divider breaking the app visually when dragged on the headerbar paned. This is fixed in this PR.

**Comment by lainsce** [comment]
Superceded by #128

**Pull request closed without merging**
