### PR TITLE
Fill in appdata

### PR DESCRIPTION
**Pull request by trst**
Addresses #141 

Took a quick crack at the copy. Super open to feedback!

Summary for tasks was taken from the elementary/tasks repository tagline/description/note (or whatever its called). I looked to the Gnome Tasks for a starting point on the Description, though I ended up going a different direction.

### CODE REVIEW

**Review by danrabbit — CHANGES_REQUESTED** [review]
Hey thanks for working on this!

This seems like a pretty good starting point. The only thing is we try to steer away from mentioning elementary OS in appdata since every app in AppCenter is made for elementary OS, so this isn't really unique and doesn't describe a differentiating feature of the app

**Comment by trst** [comment]
Fair point. Is it descriptive enough with that part of the string removed? Or should I give it a rethink?

**Comment by danrabbit** [comment]
Yeah I think that's a good starting point and we can always iterate and add more later :)

Only thing is to remove the elementary OS mention from the summary label and we're good to go!

**Comment by trst** [comment]
Doh! Should be sorted, or I’m going to eat my hat 😂

**Review by danrabbit — APPROVED** [review]
Looks good! Thanks for working on this :)

**Pull request merged**
