### PR TITLE
ListSettingsPopover: Add Mint and Bubblegum

### PR DESCRIPTION
**Pull request by danrabbit**
Supersedes #119

### CODE REVIEW

**Comment by 4jNsY6fCVqZv** [comment]
Is there a reason why you write "Add Mint and Bubblegum" but then introduce a new color name with pink?

**Comment by danrabbit** [comment]
@4jNsY6fCVqZv these aren't user-facing strings and you are missing the context of seeing the color, so it's clearer for a developer to keep it in line with the name of the style class provided by the system stylesheet

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit Then why is there any distinction at all? Wouldn't it be easier to always use the names of the style class? Or to adapt the style classes to the names of the color palette? Then it would be coherently solved at least in my perception.

**Review by marbetschar — APPROVED** [review]
Looks good to me!

**Pull request merged**
