### PR TITLE
Add missing palette colors to color button list

### LINKED ISSUE #117: Add missing palette colors to color button list
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

We've added new colors to the palette (bubblegum and mint) and they are missing from the colors selectable for tasks.

### PR DESCRIPTION
**Pull request by 4jNsY6fCVqZv**
Fixes #117

@cassidyjames Can you tell me where I can find the hexadecimal value of the checkmark white? Then I'll look at the contrasts, too.

### CODE REVIEW

**Comment by 4jNsY6fCVqZv** [comment]
Vala-lint gives four warnings for TaskModel.vala regarding "Line exceeds limit of 120 characters". Is there anything I can do? It is not caused by my changes, but I guess my Pull Request does not get a green check mark because of that.

**Comment by cassidyjames** [comment]
I think the white we use is just #fff. 😁

Re: lint, those are warnings which will still let it pass. If you scroll down a bit, it looks like there is an extra whitespace error that is causing the lint to fail.

**Comment by 4jNsY6fCVqZv** [comment]
> Re: lint, those are warnings which will still let it pass. If you scroll down a bit, it looks like there is an extra whitespace error that is causing the lint to fail.

Guess I didn't scroll all the way down here. :smile:

Took some time with Harvey, checking out the contrasts. By the way, I found some inconsistencies when comparing the hex values and the Gtk.CSS color constant in ListSettingsPopover and ColorButton.css with the values of the color palette on the website.

But first I want to focus on the contrasts: For Banana, which currently uses a color value that is not part of the color palette, no WCAG A can be achieved in any variant.  Orange, Lime & Mint would need a 700 to reach at least WCAG A. 

My question: How important is compliance here?

**Comment by 4jNsY6fCVqZv** [comment]
Can I somehow link this pull request to the corresponding issue?

**Comment by micahilbery** [comment]
yep all you have to do is write fixes #119 and GitHub will link them :+1: :slightly_smiling_face:

**Comment by 4jNsY6fCVqZv** [comment]
:smile: Thank you! @micahilbery @ryonakano 
Now I can also solve it myself in future!

**Comment by 4jNsY6fCVqZv** [comment]
Thanks for your support! @micahilbery @ryonakano

**Comment by 4jNsY6fCVqZv** [comment]
Can you please give me some hints regarding contrast and compliance? https://github.com/elementary/tasks/pull/119#issuecomment-629541008

**Comment by danrabbit** [comment]
@4jNsY6fCVqZv is this branch ready to be reviewed?

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit Before it's ready for review I would like to improve a few things that I noticed. With the topic of contrasts, I have come to a point where I would like to get some support. See https://github.com/elementary/tasks/pull/119#issuecomment-629541008
Could you imagine helping me with that?

**Comment by 4jNsY6fCVqZv** [comment]
@danrabbit When all open questions from https://github.com/elementary/calendar/pull/530 are solved, I can also adjust this draft accordingly so that it can be reviewed as well.

**Comment by danrabbit** [comment]
Closing in favor of #137

**Pull request closed without merging**
