### PR TITLE
New EntryPopover supporting Location & DateTime data types

### PR DESCRIPTION
**Pull request by marbetschar**
This PR is an initial attempt to improve the UX of Task editing (https://github.com/elementary/tasks/issues/152). I created a generic EntryPopover. In this PR I show case its usage with the newly created `DateTimePopover` and `LocationPopover` Widgets (screenshots below). Please note the `LocationPopover` is not fully complete yet, it needs some more work. Also the design details can use some more polish - but you get the idea.

Screenshot from 2020-10-24 16-06-26

Screenshot from 2020-10-24 16-06-49

@danrabbit is this related to https://github.com/elementary/tasks/pull/85?

### CODE REVIEW

**Comment by tintou** [comment]
That looks really cool

**Comment by tintou** [comment]
I often use the location field to set a URL, I don't know if that's just me or standard (in which case we should support this and don't show a map)

**Comment by marbetschar** [comment]
My intention was to allow arbitrary text in the Location field, so one can also write "Skype" or "Hangouts". Obviously this would also allow URL's. IMHO there are cases where we do want to set both, URL and location - therefore I don't think we should officially claim the location field should be used for URLs.

Isn't there a dedicated URL field in EDS? macOS Calendar does also distinguish these two fields:

Week-New

**Comment by marbetschar** [comment]
Just did a bit of digging, in the standard there are two fields (location and url). So I think we should also reflect this in our Tasks app. But we can still allow arbitrary text in the location field of course.

**VTODO**

```
todoprop   = *(
                  ...
                  ; The following are OPTIONAL,
                  ; but MUST NOT occur more than once.
                  ;
                  ... / location / ... / url / ...
```

Source:
- [RFC5545 3.6.2.  To-Do Component](https://tools.ietf.org/html/rfc5545#section-3.6.2)

**Comment by marbetschar** [comment]
trying to improve the styling of the EntryPopover - but I don't seem to be able to set the font color. In addition, the background-color does not get applied on the whole Widget, seems like if not clicked some other color is applied above. Anyone an idea how to fix this?

Styling for EntryPopover

**Comment by alainm23** [comment]
> trying to improve the styling of the EntryPopover - but I don't seem to be able to set the font color. In addition, the background-color does not get applied on the whole Widget, seems like if not clicked some other color is applied above. Anyone an idea how to fix this?
> 
> Styling for EntryPopover
> 

Try:
`
.button-css label {
    color: red;
}
`

**Comment by marbetschar** [comment]
The LocationPopover now works as well. Functionwise this is ready to merge.
Maybe someone can help with styling? Unfortunately I was not able to make the suggestion of Alain work.

**Comment by danrabbit** [comment]
Can you split this up into two branches? One for the date/time stuff and one for the location stuff? 1,000 line diff is a little bit much to review

**Comment by jlnr** [comment]
> macOS Calendar does also distinguish these two fields...

But that's only in the Calendar app; the Apple Reminders (~ elementary Tasks) has a single field for "Location".

**Comment by marbetschar** [comment]
@jlnr indeed, Apple Reminders allows to set a location to get notified on arrival or departure - but [as it turned out](https://github.com/elementary/tasks/blob/f3817889b4c78e7cfc9f3a380668ef5f2ccb2c05/src/Util.vala#L165-L196), this "notification-location" is **not** stored in the CalDAV "Location" field. The notification-location in Apple specific custom fields (`X-APPLE-PROXIMITY`, `X-APPLE-STRUCTURED-LOCATION`) within a VALARM (aka. "notification") which is in turn embedded in the VTODO (aka. "task").

I'm wondering how the behaviour is like on Android - but it seems there isn't a common ground here. So things will get messy 🥴

**Comment by marbetschar** [comment]
this PR is superseded by #159. Will create a new PR for LocationPopover once we merged the DateTimePopover.

**Comment by marbetschar** [comment]
Superseded by #174 and #159 . Closing.

**Pull request closed without merging**
