### PR TITLE
Add a task

### LINKED ISSUE #114: Can't add task with no tasks
When there are no tasks yet, we get an alert view without a way to add a new one.

image

### PR DESCRIPTION
**Pull request by marbetschar**
Replaces #97. Fixes #114 and #92.

### CODE REVIEW

**Comment by marbetschar** [comment]
@danrabbit I can't reproduce your points:

How is the task row deleteable for you? In my case its not. Also I don't encounter any duplicate issues and/or null time errors. However, I did encounter a `string_to_string: assertion 'self != NULL' failed` error message, which I fixed in the latest commit.

Below is a screencast of how the add-task feature works on my end. Can you please test how [`calcomponent_created`](https://github.com/elementary/tasks/blob/60e9fa87cba6af1147910f34f048923aa2612a51/src/Widgets/TaskRow.vala#L452) works correctly on your end? As [its ultimately used to determine if we create a new task or update an existing one](https://github.com/elementary/tasks/blob/60e9fa87cba6af1147910f34f048923aa2612a51/src/Widgets/TaskRow.vala#L200).

Screen record from 2020-05-21 17 34 47

**Comment by danrabbit** [comment]
@marbetschar can you resolve conflicts here and I'll test again? :)

**Comment by marbetschar** [comment]
@danrabbit conflicts resolved.

**Comment by marbetschar** [comment]
@danrabbit do you have the chance to verify [`calcomponent_created`'s](https://github.com/elementary/tasks/blob/60e9fa87cba6af1147910f34f048923aa2612a51/src/Widgets/TaskRow.vala#L452) behaviour on your end?

Please let me know if I can help in any way to get this resolved.

**Comment by danrabbit** [comment]
So this is what I see with this branch:

Screenshot from 2020-06-16 10 31 41@2x

Screenshot from 2020-06-16 10 31 56@2x

**Pull request merged**
